trigger:
  - master

variables:
  configuration: "Release"

jobs:
  - job: Windows
    pool:
      vmImage: "windows-2019"
    steps:
      - task: DotNetCoreCLI@2
        displayName: Restore
        inputs:
          command: restore
          projects: "**/*.csproj"

      - task: DotNetCoreCLI@2
        displayName: Build
        inputs:
          projects: "**/*.csproj"
          arguments: "--configuration $(configuration) --no-restore"

      - template: templates/test.yml
        parameters:
          configuration: ${{ variables.configuration }}
          framework: netcoreapp1.1
          platform: Windows
          collectCoverage: false

      - template: templates/test.yml
        parameters:
          configuration: ${{ variables.configuration }}
          framework: "netcoreapp2.0"
          platform: "Windows"

      - template: templates/test.yml
        parameters:
          configuration: ${{ variables.configuration }}
          framework: "netcoreapp2.2"
          platform: "Windows"

      - task: PublishBuildArtifacts@1
        displayName: Save package artifacts
        inputs:
          PathtoPublish: $(Build.ArtifactStagingDirectory)
          ArtifactName: Package

  - job: Linux
    pool:
      vmImage: "ubuntu-16.04"
    steps:
      - task: DotNetCoreCLI@2
        displayName: Restore
        inputs:
          command: restore
          projects: "**/*.csproj"

      - task: DotNetCoreCLI@2
        displayName: Build
        inputs:
          projects: "**/*.csproj"
          arguments: "--configuration $(configuration) --no-restore"

      - template: templates/test.yml
        parameters:
          configuration: ${{ variables.configuration }}
          framework: "netcoreapp1.1"
          platform: "Linux"
          collectCoverage: false

      - template: templates/test.yml
        parameters:
          configuration: ${{ variables.configuration }}
          framework: "netcoreapp2.0"
          platform: "Linux"

      - template: templates/test.yml
        parameters:
          configuration: ${{ variables.configuration }}
          framework: "netcoreapp2.2"
          platform: "Linux"

  - job: macOS
    pool:
      vmImage: "macOS-10.14"
    steps:
      - task: DotNetCoreCLI@2
        displayName: Restore
        inputs:
          command: restore
          projects: "**/*.csproj"

      - task: DotNetCoreCLI@2
        displayName: Build
        inputs:
          projects: "**/*.csproj"
          arguments: "--configuration $(configuration) --no-restore"

      - template: templates/test.yml
        parameters:
          configuration: ${{ variables.configuration }}
          framework: "netcoreapp1.1"
          platform: "macOS"
          collectCoverage: false

      - template: templates/test.yml
        parameters:
          configuration: ${{ variables.configuration }}
          framework: "netcoreapp2.0"
          platform: "macOS"

      - template: templates/test.yml
        parameters:
          configuration: ${{ variables.configuration }}
          framework: "netcoreapp2.2"
          platform: "macOS"
